---
-
  name: "Create backend in backend service '{{ backend_service.name }}'"
  shell: |
    gcloud beta compute backend-services add-backend {{ backend_service.name }} \
    --instance-group={{ backend.instance_group }} \
    --description="backend.description|default('Backend for backend service \'{{ backend_service.name }}\'') [autogen:{{ range(0, 500)|random }}]" \
    {% if backend.balancing_mode is defined %} --balancing-mode={{ backend.balancing_mode|upper }} {% endif %} \
    {% if backend_service.global|default(True) %} --global {% endif %} \
    {% if backend_service.region|default(False) %} --region={{ backend_service.region }} {% endif %} \
    {% if backend_service.global is defined and backend_service.global %} --global {% endif %} \
    {% if backend_service.region is defined %} --region={{ backend_service.region }} {% endif %} \
    {% if backend.zone is defined %} --instance-group-zone={{ backend.zone }} {% endif %} \
    {% if backend.region is defined %} --instance-group-region={{ backend.region }} {% endif %}