---
-
  name: "Create backend service '{{ backend_service.name }}'."
  shell: |
    gcloud beta compute backend-services create {{ backend_service.name }} \
    {% if backend_service.global is defined and backend_service.global %} --global {% endif %} \
    {% if backend_service.region is defined %} --region={{ backend_service.region }} {% endif %} \
    {% if backend_service.affinity_cookie_ttl is defined %} --affinity-cookie-ttl={{ backend_service.affinity_cookie_ttl }} {% endif %} \
    {% if backend_service.connection_draining is defined %} --connection-draining-timeout={{ backend_service.connection_draining }} {% endif %} \
    {% if backend_service.description is defined %} --description={{ backend_service.description }} {% endif %} \
    {% if backend_service.enable_cdn|default(false) %} --enable-cdn {% endif %} \
    {% if backend_service.health_checks is defined %} --health-checks={{ backend_service.health_checks|join(',') }} {% endif %} \
    {% if backend_service.http_health_checks is defined %} --http-health-checks={{ backend_service.http_health_checks|join(',') }} {% endif %} \
    {% if backend_service.https_health_checks is defined %} --https-health-checks={{ backend_service.https_health_checks|join(',') }} {% endif %} \
    --load-balancing-scheme={{ backend_service.load_balancing_scheme|default('external')|upper }} \
    --port-name={{ backend_service.port_name|default('http') }} \
    --protocol={{ backend_service.protocol|upper }} \
    --session-affinity={{ backend_service.session_affinity|default('none')|upper }} \
    --timeout={{ backend_service.timeout|default('10s') }} \
    {% if backend_service.port_name is defined %} --https-health-checks={{ backend_service.https_health_checks|join(',') }} {% endif %} \
