---
-
  name: "Delete backend service '{{ backend_service.name }}'"
  shell: |
    gcloud beta compute backend-services delete {{ backend_service.name }} -q \
    {% if backend_service.global|default(false) %} --global {% endif %} \
    {% if backend_service.region|default(false) %} --region={{ backend_service.region }} {% endif %}