---
# Create addresse.
-
  name: Create reserved addresses.
  with_items: "{{ gcloud_compute_addresses }}"
  when: address.state|default('present') == 'present'
  include: addresses/create.yaml
  loop_control:
    loop_var: address
-
  name: Manage networks.
  with_items: "{{ gcloud_compute_networks }}"
  when: network.state|default('present') == 'present'
  include: networks/manage.yaml
  loop_control:
    loop_var: network
-
  when: gcloud_compute_health_checks|length > 0
  with_items: "{{ gcloud_compute_health_checks }}"
  include: health_checks/main.yaml
-
  when: gcloud_compute_http_health_checks|length > 0
  with_items: "{{ gcloud_compute_http_health_checks }}"
  include: http_health_checks.yaml
-
  name: Manage instance groups.
  when: gcloud_compute_instance_groups|length > 0
  with_items: "{{ gcloud_compute_instance_groups }}"
  include: instance_groups.yaml
-
  name: Managed backend services.
  when: gcloud_compute_backend_services|length > 0
  with_items: "{{ gcloud_compute_backend_services }}"
  include: backend_services.yaml

# Delete items.

-
  name: Delete networks.
  with_items: "{{ gcloud_compute_networks }}"
  when: network.state|default('present') == 'absent'
  include: networks/delete.yaml
  loop_control:
    loop_var: network
-
  name: Delete reserved addresses.
  with_items: "{{ gcloud_compute_addresses }}"
  when: address.state|default('present') == 'absent'
  include: addresses/delete.yaml
  loop_control:
    loop_var: address