---
-
  name: Manage reserved addresses.
  when: gcloud_compute_addresses|length > 0
  with_items: "{{ gcloud_compute_addresses }}"
  include: addresses/main.yaml
  loop_control:
    loop_var: address
-
  name: Manage networks.
  when: gcloud_compute_networks|length > 0
  with_items: "{{ gcloud_compute_networks }}"
  include: networks.yaml
-
  name: Manage health checks
  when: gcloud_compute_health_checks|length > 0
  with_items: "{{ gcloud_compute_health_checks }}"
  include: health_checks/main.yaml
-
  name: Manage instance groups.
  when: gcloud_compute_instance_groups|length > 0
  with_items: "{{ gcloud_compute_instance_groups }}"
  include: instance_groups.yaml