---
-
  set_fact:
    network: "{{ item }}"
-
  name: "Check if network '{{ item.name }}' exists."
  shell: gcloud beta compute networks list --format=json --filter="name = {{ network.name }}"
  register: __gcloud_compute_existing_network__
  changed_when: false

# Create a new network.
-
  include: networks/create.yaml
  when: __gcloud_compute_existing_network__.stdout == '[]' and network.state|default('present') == 'present'

# Update an existing network.
-
  include: networks/update.yaml
  when: __gcloud_compute_existing_network__.stdout != '[]' and network.state|default('present') == 'present'

# Delete a network.
-
  include: networks/delete.yaml
  when: __gcloud_compute_existing_network__.stdout != '[]' and network.state|default('present') == 'absent'
