---
-
  name: Check whether address exists.
  register: __gcloud_compute_existing_address__
  shell: gcloud beta compute addresses list --format=json --filter="name = {{ address.name }}"
  changed_when: false
-
  name: "Create reserved address {{ address.name }}"
  when: __gcloud_compute_existing_address__.stdout == '[]' and address.state|default('present') == 'present'
  shell: |
    gcloud beta compute addresses create {{ address.name }} \
    {% if address.addresses is defined %} --addresses={{ address.addresses|join(',') }} {% endif %} \
    {% if address.global|default(False) %} --global {% endif %} \
    {% if address.region is defined %} --region={{ address.region }} {% endif %}
-
  name: "Delete reserved address {{ address.name }}."
  when: __gcloud_compute_existing_address__.stdout != '[]' and address.state|default('present') == 'absent'
  shell: |
    gcloud beta compute addresses delete {{ address.name }} \
    {% if address.global|default(False) %} --global {% endif %} \
    {% if address.region is defined %} --region={{ address.region }} {% endif %}