---
-
  name: "List current firewall rules for network '{{ network.name }}'."
  register: __gcloud_compute_existing_firewall_rules__
  shell: gcloud beta compute firewall-rules list --format=json --filter="network = {{ network.name }}"
  changed_when: false
-
  name: "Create firewall rules for network '{{ network.name }}'."
  when: item.state|default('present') == 'present' and network.name + '-' + item.name not in __gcloud_compute_existing_firewall_rules__.stdout|from_json|map(attribute='name')|list
  shell: |
    gcloud beta compute firewall-rules create {{ network.name }}-{{ item.name }} \
    --network="{{ network.name }}" \
    --allow {{ item.allow|join(",") }} \
    {% if item.description is defined %} --description="{{ item.description }}" {% endif %} \
    {% if item.source_tags|default([])|length > 0 %} --source-tags={{ item.source_tags|join(",") }} {% endif %} \
    {% if item.source_ranges|default([])|length > 0 %} --source-ranges={{ item.source_ranges|join(",") }} {% endif %} \
    {% if item.target_tags|default([])|length > 0 %} --target-tags={{ item.target_tags|join(",") }} {% endif %}
  with_items: "{{ network.firewall_rules }}"
-
  name: "Update firewall rules for network '{{ network.name }}'."
  when: item.state|default('present') == 'present' and network.name + '-' + item.name in __gcloud_compute_existing_firewall_rules__.stdout|from_json|map(attribute='name')|list
  with_items: "{{ network.firewall_rules }}"
  shell: |
    gcloud beta compute firewall-rules update {{ network.name }}-{{ item.name }} \
    --allow {{ item.allow|join(",") }} \
    {% if item.description is defined %} --description="{{ item.description }}" {% endif %} \
    {% if item.source_tags|default([])|length > 0 %} --source-tags={{ item.source_tags|join(",") }} {% endif %} \
    {% if item.source_ranges|default([])|length > 0 %} --source-ranges={{ item.source_ranges|join(",") }} {% endif %} \
    {% if item.target_tags|default([])|length > 0 %} --target-tags={{ item.target_tags|join(",") }} {% endif %}
-
  name: "Remove firewall rules for network '{{ network.name }}'."
  when: item.state|default('present') == 'absent' and network.name + '-' + item.name in __gcloud_compute_existing_firewall_rules__.stdout|from_json|map(attribute='name')|list
  shell: gcloud beta compute firewall-rules delete {{ network.name }}-{{ item.name }}
  with_items: "{{ network.firewall_rules }}"


#gcloud beta compute firewall-rules \
#    {% if network.name + '-' + item.name in __firewall_rules__.stdout|from_json|map(attribute='name')|list %} \
#      update {{ network.name }}-{{ item.name }} \
#    {% else %} \
#      create {{ network.name }}-{{ item.name }} --network="{{ network.name }}" \
#    {% endif %} \
#    --allow {{ item.allow|join(",") }} \
#    {% if item.source_tags|default([])|length > 0 %} --source-tags={{ item.source_tags|join(",") }} {% endif %} \
#    {% if item.source_ranges|default([])|length > 0 %} --source-ranges={{ item.source_ranges|join(",") }} {% endif %} \
#    {% if item.target_tags|default([])|length > 0 %} --target-tags={{ item.target_tags|join(",") }} {% endif %}