---
-
  name: "Create managed instance group '{{ instance_group.name }}'."
  when: instance_group.managed
  shell: |
    gcloud beta compute instance-groups managed create {{ instance_group.name }} \
    --size={{ instance_group.size }} \
    --template={{ instance_group.template }} \
    {% if instance_group.base_instance_name is defined %} --base-instance-name={{ instance_group.base_instance_name }} {% endif %} \
    {% if instance_group.description is defined %} --description={{ instance_group.description }} {% endif %} \
    {% if instance_group.initial_delay is defined %} --initial-delay={{ instance_group.initial_delay }}s {% endif %} \
    {% if instance_group.target_pools is defined %} --target-pool={{ instance_group.target_pools|join(',') }} {% endif %} \
    {% if instance_group.http_health_check is defined %} --http-health-check={{ instance_group.http_health_check }} {% endif %} \
    {% if instance_group.https_health_check is defined %} --https-health-check={{ instance_group.https_health_check }} {% endif %} \
    {% if instance_group.region is defined %} --region={{ instance_group.region }} {% endif %} \
    {% if instance_group.zone is defined %} --region={{ instance_group.zone }} {% endif %}

-
  name: "Create unmanaged instance group '{{ instance_group.name }}'."
  when: not instance_group.managed
  shell: |
    gcloud beta compute instance-groups unmanaged create {{ instance_group.name }} \
    {% if instance_group.description is defined %} --description="{{ instance_group.description }}" {% endif %} \
    {% if instance_group.zone is defined %} --zone="{{ instance_group.zone }}" {% endif %}